date.timezone = "Asia/Tokyo"

; 修正: 1つのアップロードファイルの最大サイズ
upload_max_filesize = 10M

; 修正: フォーム全体の送信サイズ
post_max_size = 10M

[mbstring]
mbstring.internal_encoding = "UTF-8"
mbstring.language = "Japanese"